"""empty message

Revision ID: 9fa3cbbcb34b
Revises: b979e6aeb4a1
Create Date: 2020-01-26 16:21:24.115397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa3cbbcb34b'
down_revision = 'b979e6aeb4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_name_phone_key', 'artist', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('artist_name_phone_key', 'artist', ['name', 'phone'])
    # ### end Alembic commands ###
