"""empty message

Revision ID: aac6bcc3062a
Revises: 64f700a21ff8
Create Date: 2020-01-24 23:46:56.866955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac6bcc3062a'
down_revision = '64f700a21ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist', ['name', 'phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='unique')
    # ### end Alembic commands ###
