"""empty message

Revision ID: b979e6aeb4a1
Revises: aac6bcc3062a
Create Date: 2020-01-25 12:20:09.556264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b979e6aeb4a1'
down_revision = 'aac6bcc3062a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_name_phone_key', 'artist', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('artist_name_phone_key', 'artist', ['name', 'phone'])
    # ### end Alembic commands ###
