"""empty message

Revision ID: bc70a1d0180f
Revises: a7807ed01df0
Create Date: 2020-01-24 14:13:10.384096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc70a1d0180f'
down_revision = 'a7807ed01df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('artist_genre', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artist_genre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artist_venue', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artist_venue', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_genre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_genre', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_genre', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venue_genre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artist_venue', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artist_venue', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artist_genre', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artist_genre', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('show')
    # ### end Alembic commands ###
