"""empty message

Revision ID: cb3796a5c90c
Revises: 9fa3cbbcb34b
Create Date: 2020-01-27 22:07:26.352952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3796a5c90c'
down_revision = '9fa3cbbcb34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'upcoming_shows')
    # ### end Alembic commands ###
